Add test job to build-dockerize.yml

diff --git a/.github/workflows/build-dockerize.yml b/.github/workflows/build-dockerize.yml
--- a/.github/workflows/build-dockerize.yml
+++ b/.github/workflows/build-dockerize.yml
@@ -13,6 +13,39 @@ env:
   TAG: latest
 
 jobs:
+
+  test:
+    
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout Repo
+      uses: actions/checkout@v2
+    - name: Cache NPM dependencies
+      uses: actions/cache@v1
+      with:
+        path: '**/node_modules'
+        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
+        restore-keys: |
+          ${{ runner.OS }}-npm-cache-
+    - name: Run yarn install
+      run: yarn install --fixed-lockfile
+    - name: Run tests 
+      run: yarn ci:test
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: junit.xml    # Path to test results
+        reporter: jest-junit
+    - name: SonarCloud Scan
+      uses: SonarSource/sonarcloud-github-action@master
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+    
   build:
 
     runs-on: ubuntu-latest
@@ -31,15 +64,6 @@ jobs:
       run: yarn install --fixed-lockfile
     - name: Run build
       run: yarn build
-    - name: Run tests 
-      run: yarn ci:test
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: JEST Tests            # Name of the check run which will be created
-        path: junit.xml    # Path to test results
-        reporter: jest-junit
     - name: Archive production artifacts
       uses: actions/upload-artifact@v2
       with:
@@ -51,7 +75,10 @@ jobs:
           yarn.lock
 
   dockerize:
-    needs: build
+    needs: 
+      - build
+      - test
+    
     runs-on: ubuntu-latest
 
     steps: 
