Add test result display for github actions

diff --git a/.github/workflows/build-dockerize.yml b/.github/workflows/build-dockerize.yml
--- a/.github/workflows/build-dockerize.yml
+++ b/.github/workflows/build-dockerize.yml
@@ -32,7 +32,14 @@ jobs:
     - name: Run build
       run: yarn build
     - name: Run tests 
-      run: yarn test
+      run: yarn ci:test
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: junit.xml    # Path to test results
+        reporter: jest-junit
     - name: Archive production artifacts
       uses: actions/upload-artifact@v2
       with:
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,4 +23,11 @@ jobs:
     - name: Run yarn install
       run: yarn install --fixed-lockfile
     - name: Run tests 
-      run: yarn test
+      run: yarn ci:test
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: junit.xml    # Path to test results
+        reporter: jest-junit
